### ISSUE TITLE
Implement Login.gov Flow for New and Existing User

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#124] opened 2022-09-15 18:15 UTC
_Outcome_: 
1. A new user can come to the site, click a "login" button, create a user account and land on a /whoami page. 
2. An existing user can come to the site, click a "login" button, and be redirected to the /whoami page.

- [ ] Backend implementation
- [ ] Frontend implementation
- [ ] oidc wrapper

**Comment by loganmeetsworld** [comment] 2022-09-16 16:36
Duplicate of #15

**Closed by loganmeetsworld** 2022-09-16 16:36 UTC
Labels: sprint goal, dev
