### ISSUE TITLE
Bug: User Facing login page after providing credentials

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#405] opened 2023-02-08 20:54 UTC
**Background**

- When doing user testing, when the user used a bulk login 
- List of logins: https://docs.google.com/spreadsheets/d/1QkK4oXhc5Cum37N9v9_vcEUePmgpAkF_h66qyl6wJ3Y/edit?usp=sharing
- After logging in at https://getgov-stable.app.cloud.gov/, they were prompted back to that page - clicking sign in brought them to the registrar
- Did not get this when using my own login

**Comment by calerubensteingsa** [comment] 2023-04-17 14:52
May no longer be needed

**Comment by loganmeetsworld** [comment] 2023-04-28 16:42
It is still needed since @neilmb hit it yesterday - may be hard to reproduce

**Comment by igorkorenfeld** [comment] 2023-04-28 17:50
Encountered this bug today, here are the steps that led me to it:

1. Was signed in the MR workspace
2. Needed to run migrations
3. After running migrations got an “Unauthorized error” with a unique identifier
4. Clicked “Would you like to try logging in again”
5. Went through [Login.gov](http://login.gov/) flow
6. Got dropped back to https://getgov-mr.app.cloud.gov/
7. Presented with “Sign in” button
8. Pressing “Sign in” immediately dropped me into the dashboard

**Comment by igorkorenfeld** [comment] 2023-05-09 19:11
Ran into this issue again today in the `rjm` sandbox. This time I didn't run migrations. It was was my first time logging in on this sandbox. 

1. Clicked the sandbox link in the Github PR
1. Logged in with Login
2. Presented with "Sign in" button
3. Clicking immediately dropped me into the dashboard. 

Unfortunately I can't remember if the link took me straight to Login or to the Sign in page.

**Comment by rachidatecs** [comment] 2023-05-30 21:43
I think this an be reproduced when logging in for the first time (user + environment combo is new)

**Comment by zandercymatics** [comment] 2023-09-01 19:45
Assigned to myself per Pauls request

**Comment by zandercymatics** [comment] 2023-09-08 05:53
I heavily suspect this issue was related to the 'Issued in the Future' bug with our time skew. See [here](https://github.com/cisagov/getgov/pull/960). This same behavior was noted there and increased in frequency overtime. On stable (and any sandbox up to date with the commit that fixes this bug), I cannot replicate this behavior. However, on older sandboxes (without the fix), I can get this to reappear. 

From what I can tell, it does not correlate to what account you are using, rather it correlates with oidc being out of date with login.gov - which happens unpredictably. You can increase the likelihood of this happening by doing mass-logins because this bug would only occur during login, not while you are logged in. So, its like rolling two six-sided dies hoping for snake eyes - it'll probably happen if you do it enough times in a row.

I would suggest closing this issue.

**Comment by zandercymatics** [comment] 2023-09-08 05:54
@PaulKuykendall See above ^^

**Comment by PaulKuykendall** [comment] 2023-09-25 22:52
@abroddrick - I will close this bug per Zander's assessment. Any objection?

**Comment by abroddrick** [comment] 2023-09-26 04:03
Nope, I am on board with closing it

**Closed** 2023-09-29 14:00 UTC
Labels: dev, bug, MVP
