### ISSUE TITLE
Support educational content for election new registrants

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#112] opened 2022-09-07 20:31 UTC
- [ ] Clarify scope of support we'll provide for election offices (e.g., Will they have their own points of contact, path through the system?)
- [ ] Draft content
- [ ] Share for review and comment

Objective: Support content for new registrants who are registering an election site

**Comment by calerubensteingsa** [comment] 2022-09-27 14:13
9/27:

- Started yesterday, based on convo with Ryan, just looking at source content - probably already in a no change mode
- Should that impact the priority of this content? No other audience looking to take priority away

**Comment by calerubensteingsa** [comment] 2022-10-20 14:18
10/20

- Nothing else happening for election offices
- Going to talk to more people, continue to be stakeholder

**Comment by michelle-rago** [comment] 2023-01-23 20:15
Dupe of #305

**Closed by michelle-rago** 2023-01-23 20:15 UTC
Labels: content
